description: >
  The circleci-cli Docker image, which includes the CircleCI CLI executable.

parameters:
  tag:
    type: string
    default: "0.1.26646"
    description: >
      What version of the CircleCI CLI Docker image? For full list, see
      https://hub.docker.com/r/circleci/circleci-cli/tags
  resource_class:
    description: Configure the executor resource class
    type: enum
    enum: ["small", "medium", "medium+", "large", "xlarge", "2xlarge", "2xlarge+"]
    default: "medium"
  circleci_ip_ranges:
    description: Enables jobs to go through a set of well-defined IP address ranges.
    type: boolean
    default: false

resource_class: << parameters.resource_class >>
docker:
  - image: circleci/circleci-cli:<< parameters.tag >>
